#!/usr/bin/env python3
"""Generate and validate the tagged table of contents over docs/knowledge/notes/.

Each note carries a `bookmarks:` frontmatter key. Two states are distinct and
both valid:

- missing the `bookmarks:` key entirely  -> note has not been reviewed yet.
- `bookmarks: []` (explicit empty list)   -> reviewed, deliberately nothing noteworthy.

`BOOKMARKS.md` is a hand-authored allow-list (a markdown table, one row per
bookmark) — this script only *reads* it to validate against, it never writes
to it. `INDEX.md` is the one generated artifact; regenerate it with no
arguments after editing any note's frontmatter.

Usage:
    python3 scripts/notes/index.py                        # regenerate INDEX.md
    python3 scripts/notes/index.py --check                 # exit non-zero if stale/invalid (for CI)
    python3 scripts/notes/index.py --apply-bookmarks <map.json>  # one-shot backfill (WU2)
"""

import json
import re
import subprocess
import sys
from pathlib import Path
from typing import Dict, List, Optional, Set, Tuple

REPO_ROOT = Path(__file__).resolve().parents[2]
NOTES_DIR = REPO_ROOT / "docs" / "knowledge" / "notes"
BOOKMARKS_FILE = NOTES_DIR / "BOOKMARKS.md"
INDEX_FILE = NOTES_DIR / "INDEX.md"
EXCLUDED_FILES = {"TEMPLATE.md", "BOOKMARKS.md", "INDEX.md"}

FRONTMATTER_RE = re.compile(r"\A---\n(.*?)\n---\n", re.DOTALL)
BOOKMARKS_KEY_RE = re.compile(r"^bookmarks:\s*\[(.*)\]\s*$", re.MULTILINE)
BLOCK_STYLE_KEY_RE = re.compile(r"^bookmarks:\s*$", re.MULTILINE)
VOCAB_ROW_RE = re.compile(r"^\|\s*`?([^`|]+?)`?\s*\|")
KEBAB_RE = re.compile(r"^[a-z0-9]+(-[a-z0-9]+)*$")

GENERATED_BANNER = "<!-- Generated by scripts/notes/index.py — do not edit by hand -->"


def _tracked_note_names(notes_dir: Path) -> Optional[Set[str]]:
    """Names of git-tracked (or staged) .md files directly in notes_dir, or
    None if git is unavailable (not a repo, no git binary) — callers then
    fall back to including every file on disk, matching the pre-HAB-250
    behaviour."""
    try:
        result = subprocess.run(
            # core.quotePath=false + -z: NUL-separated, unescaped filenames —
            # otherwise a non-ASCII name comes back octal-quoted (e.g.
            # "HAB-\303\251.md") and would silently fail every p.name match.
            ["git", "-c", "core.quotePath=false", "ls-files", "-z", "*.md"],
            cwd=notes_dir,
            capture_output=True,
            text=True,
            encoding="utf-8",
            check=True,
        )
    except (OSError, subprocess.CalledProcessError):
        return None
    return {name for name in result.stdout.split("\0") if name}


def iter_notes(notes_dir: Path) -> List[Path]:
    """All note files in scan order, excluding the template and generated
    files. Restricted to git-tracked (or staged) files when git is available
    — an untracked .md file (e.g. a note being drafted for a different,
    not-yet-committed ticket) must never leak into the generated INDEX.md,
    since CI's checkout never has it (HAB-248, HAB-250)."""
    tracked = _tracked_note_names(notes_dir)
    candidates = notes_dir.glob("*.md")
    if tracked is not None:
        candidates = (p for p in candidates if p.name in tracked)
    return sorted(p for p in candidates if p.name not in EXCLUDED_FILES)


def parse_note(path: Path) -> Tuple[bool, List[str]]:
    """Return (has_bookmarks_key, bookmarks). has_bookmarks_key is False when
    the file has no frontmatter block, or the block has no `bookmarks:` key
    in the supported inline-list form (see detect_malformed_bookmarks for the
    block-style-list case, which is reported separately as a format error
    rather than silently treated as "missing")."""
    text = path.read_text(encoding="utf-8")
    match = FRONTMATTER_RE.match(text)
    if not match:
        return False, []
    key_match = BOOKMARKS_KEY_RE.search(match.group(1))
    if not key_match:
        return False, []
    raw = key_match.group(1).strip()
    if not raw:
        return True, []
    items = [item.strip().strip("'\"") for item in raw.split(",")]
    return True, [item for item in items if item]


def detect_malformed_bookmarks(path: Path) -> Optional[str]:
    """Return an error string if the note uses an unsupported bookmarks:
    format (currently: YAML block-list style) instead of the inline-list
    form this tool understands, else None."""
    text = path.read_text(encoding="utf-8")
    match = FRONTMATTER_RE.match(text)
    if not match:
        return None
    frontmatter = match.group(1)
    if BOOKMARKS_KEY_RE.search(frontmatter):
        return None
    if BLOCK_STYLE_KEY_RE.search(frontmatter):
        return "bookmarks: uses block-list style ('- item' lines) — use the inline form instead: bookmarks: [item-one, item-two]"
    return None


def _is_separator_row(line: str) -> bool:
    """A markdown table separator/divider row (e.g. `|---|---|`)."""
    stripped = line.strip()
    return stripped.startswith("|") and all(ch in "|:- " for ch in stripped)


def _scan_vocabulary_rows(vocab_file: Path) -> Tuple[Set[str], List[str]]:
    """Scan BOOKMARKS.md's table rows, splitting into (valid kebab-case
    names, malformed tokens that don't fit the naming convention)."""
    if not vocab_file.exists():
        return set(), []
    valid: Set[str] = set()
    malformed: List[str] = []
    for line in vocab_file.read_text(encoding="utf-8").splitlines():
        if _is_separator_row(line):
            continue
        match = VOCAB_ROW_RE.match(line)
        if not match:
            continue
        token = match.group(1).strip()
        if not token or token.lower() == "bookmark":
            continue
        if KEBAB_RE.match(token):
            valid.add(token)
        else:
            malformed.append(token)
    return valid, malformed


def load_vocabulary(vocab_file: Path) -> Set[str]:
    """Parse the hand-authored bookmark allow-list from its markdown table.
    Rows that don't fit the lowercase-kebab-case convention are dropped here
    — use validate_vocabulary() to surface those as loud errors instead."""
    valid, _ = _scan_vocabulary_rows(vocab_file)
    return valid


def validate_vocabulary(vocab_file: Path) -> List[str]:
    """Return error strings for BOOKMARKS.md rows that don't fit the
    lowercase-kebab-case convention, so a typo doesn't silently vanish and
    resurface as a confusing "unknown bookmark" error on some other note."""
    _, malformed = _scan_vocabulary_rows(vocab_file)
    return [
        f"BOOKMARKS.md: '{token}' is not a valid bookmark name "
        f"(must be lowercase-kebab-case) — fix or remove this row"
        for token in malformed
    ]


def render_index(notes_dir: Path, vocab_file: Path) -> str:
    """Deterministically render INDEX.md content from the current corpus."""
    vocabulary = load_vocabulary(vocab_file)
    by_bookmark: Dict[str, List[Tuple[str, str]]] = {b: [] for b in sorted(vocabulary)}
    reviewed_empty: List[Tuple[str, str]] = []
    not_yet_reviewed: List[Tuple[str, str]] = []

    for note in iter_notes(notes_dir):
        text = note.read_text(encoding="utf-8")
        title_match = re.search(r"^#\s+(.+)$", text, re.MULTILINE)
        title = title_match.group(1).strip() if title_match else note.stem
        has_key, bookmarks = parse_note(note)
        if not has_key:
            not_yet_reviewed.append((note.name, title))
            continue
        if not bookmarks:
            reviewed_empty.append((note.name, title))
            continue
        for bookmark in bookmarks:
            by_bookmark.setdefault(bookmark, []).append((note.name, title))

    lines = [GENERATED_BANNER, "", "# Notes index", "",
             "Generated from `bookmarks:` frontmatter in `docs/knowledge/notes/*.md`. "
             "Run `python3 scripts/notes/index.py` after tagging changes.", ""]

    lines.append("## Top themes")
    lines.append("")
    ranked = sorted(((b, notes) for b, notes in by_bookmark.items() if notes),
                     key=lambda pair: (-len(pair[1]), pair[0]))
    for bookmark, notes in ranked:
        lines.append(f"- **{bookmark}** ({len(notes)})")
    lines.append("")

    lines.append("## By bookmark")
    lines.append("")
    for bookmark in sorted(by_bookmark):
        notes = by_bookmark[bookmark]
        if not notes:
            continue
        lines.append(f"### {bookmark}")
        for filename, title in sorted(notes):
            lines.append(f"- [{title}]({filename})")
        lines.append("")

    if reviewed_empty:
        lines.append("## Reviewed — nothing noteworthy")
        lines.append("")
        for filename, title in sorted(reviewed_empty):
            lines.append(f"- [{title}]({filename})")
        lines.append("")

    if not_yet_reviewed:
        lines.append("## Not yet reviewed")
        lines.append("")
        for filename, title in sorted(not_yet_reviewed):
            lines.append(f"- [{title}]({filename})")
        lines.append("")

    return "\n".join(lines).rstrip("\n") + "\n"


def write_index(notes_dir: Path, vocab_file: Path, index_file: Path) -> None:
    index_file.write_text(render_index(notes_dir, vocab_file), encoding="utf-8")


def check(notes_dir: Path, vocab_file: Path, index_file: Path) -> List[str]:
    """Return a list of validation errors (empty list = clean)."""
    errors = list(validate_vocabulary(vocab_file))
    vocabulary = load_vocabulary(vocab_file)

    for note in iter_notes(notes_dir):
        malformed = detect_malformed_bookmarks(note)
        if malformed:
            errors.append(f"{note.name}: {malformed}")
            continue
        has_key, bookmarks = parse_note(note)
        if not has_key:
            errors.append(
                f"{note.name}: missing 'bookmarks:' key "
                f"(use bookmarks: [] if genuinely nothing noteworthy applies)"
            )
            continue
        for bookmark in bookmarks:
            if bookmark not in vocabulary:
                errors.append(f"{note.name}: unknown bookmark '{bookmark}' — add it to BOOKMARKS.md first")

    expected = render_index(notes_dir, vocab_file)
    actual = index_file.read_text(encoding="utf-8") if index_file.exists() else None
    if actual != expected:
        errors.append("INDEX.md is stale — run `python3 scripts/notes/index.py` to regenerate")

    return errors


def apply_bookmarks(
    notes_dir: Path, mapping: Dict[str, List[str]], vocab_file: Optional[Path] = None
) -> Dict[str, str]:
    """One-shot backfill: insert a `bookmarks:` frontmatter block into each
    named file, in place. Never touches a file that already has the key.

    Validates the entire mapping — every filename resolves to a real file
    inside notes_dir (not excluded, not a path escape), and every bookmark
    is in the vocabulary when vocab_file is given — before writing anything,
    so a bad entry aborts the whole run rather than leaving it half-applied.

    Returns {filename: "applied" | "skipped-already-tagged"}.
    """
    vocabulary = load_vocabulary(vocab_file) if vocab_file is not None else None
    resolved_notes_dir = notes_dir.resolve()

    for filename, bookmarks in mapping.items():
        if filename in EXCLUDED_FILES or Path(filename).name != filename:
            raise ValueError(f"{filename}: not a valid note file for backfill")
        path = notes_dir / filename
        if not path.exists() or path.resolve().parent != resolved_notes_dir:
            raise ValueError(f"{filename}: not found in {notes_dir}")
        if vocabulary is not None:
            for bookmark in bookmarks:
                if bookmark not in vocabulary:
                    raise ValueError(f"{filename}: unknown bookmark '{bookmark}' — add it to BOOKMARKS.md first")

    outcomes: Dict[str, str] = {}
    for filename, bookmarks in mapping.items():
        path = notes_dir / filename
        has_key, _ = parse_note(path)
        if has_key:
            outcomes[filename] = "skipped-already-tagged"
            continue
        text = path.read_text(encoding="utf-8")
        frontmatter_match = FRONTMATTER_RE.match(text)
        if frontmatter_match:
            new_frontmatter = frontmatter_match.group(1) + f"\nbookmarks: [{', '.join(bookmarks)}]"
            body = f"---\n{new_frontmatter}\n---\n" + text[frontmatter_match.end():]
        else:
            body = f"---\nbookmarks: [{', '.join(bookmarks)}]\n---\n\n" + text
        path.write_text(body, encoding="utf-8")
        outcomes[filename] = "applied"
    return outcomes


def main(argv: List[str]) -> int:
    if not NOTES_DIR.exists():
        print(f"Notes directory not found: {NOTES_DIR}", file=sys.stderr)
        return 2

    mode = argv[0] if argv else None

    if mode is None:
        write_index(NOTES_DIR, BOOKMARKS_FILE, INDEX_FILE)
        print(f"Regenerated {INDEX_FILE}")
        return 0

    if mode == "--check":
        errors = check(NOTES_DIR, BOOKMARKS_FILE, INDEX_FILE)
        if errors:
            for error in errors:
                print(f"ERROR: {error}", file=sys.stderr)
            return 1
        print("OK")
        return 0

    if mode == "--apply-bookmarks":
        if len(argv) < 2:
            print("Usage: index.py --apply-bookmarks <mapping.json>", file=sys.stderr)
            return 2
        mapping_file = Path(argv[1])
        if not mapping_file.exists():
            print(f"Mapping file not found: {mapping_file}", file=sys.stderr)
            return 2
        mapping = json.loads(mapping_file.read_text(encoding="utf-8"))
        try:
            outcomes = apply_bookmarks(NOTES_DIR, mapping, BOOKMARKS_FILE)
        except ValueError as exc:
            print(f"ERROR: {exc}", file=sys.stderr)
            return 1
        applied = sum(1 for v in outcomes.values() if v == "applied")
        skipped = sum(1 for v in outcomes.values() if v == "skipped-already-tagged")
        print(f"Applied bookmarks to {applied} file(s); skipped {skipped} already-tagged file(s).")
        write_index(NOTES_DIR, BOOKMARKS_FILE, INDEX_FILE)
        return 0

    print(f"Unknown mode: {mode}", file=sys.stderr)
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
